function TabOrient({ ctx }) {
  const {
    aba,
    setAba,
    modalidade,
    setModalidade,
    atend,
    setAtend,
    prop,
    setProp,
    corr,
    setCorr,
    obra,
    setObra,
    gerador,
    setGerador,
    obs,
    setObs,
    cepStatus,
    setCepStatus,
    cnpjStatus,
    setCnpjStatus,
    logoPDF,
    setLogoPDF,
    ucsDet,
    setUcsDet,
    ucBlocos,
    setUcBlocos,
    blocos,
    setBlocos,
    abas,
    buscarCEP,
    buscarCNPJ,
    coletivo,
    coordObrigatoria,
    coordPreenchida,
    demandaPrevTotal,
    demandaTotalGeral,
    disjGeralObrigatorio,
    docInfo,
    gerarPDF,
    hibrido,
    idx,
    irAnt,
    irProx,
    isAlteracaoColetivo,
    maiorCorrenteUC,
    multiTorres,
    opcoesDisjGeral,
    pessoaFisica,
    prevTotalKw,
    redeMono,
    replicarPrevTodas,
    replicarPrevTorre,
    replicarPrimeiro,
    replicarUC1Coletivo,
    replicarUC1Torre,
    setBloco,
    setBlocoPrev,
    setTorre,
    setUcDet,
    setUcTorre,
    setUcTorrePrev,
    sincronizarUCsTorre,
    restrito,
    totalUcsEmpreendimento,
    trocaDisjGeral,
    validacaoDisjuntores,
    validacaoHibrido,
  } = ctx;
  return /* @__PURE__ */ React.createElement(
    Card,
    {
      eyebrow: "Etapa " + ctx.etapaNum,
      title: "Orientações para preenchimento",
      sub: ORIENTACOES.intro,
    },
    /* @__PURE__ */ React.createElement(
      "div",
      {
        style: {
          fontWeight: 700,
          color: "var(--verde-escuro)",
          fontSize: 14,
          marginBottom: 4,
        },
      },
      ORIENTACOES.geral.titulo,
    ),
    /* @__PURE__ */ React.createElement(
      "ul",
      { className: "orient-list" },
      ORIENTACOES.geral.itens.map((it, i) =>
        /* @__PURE__ */ React.createElement(
          "li",
          { key: i, className: "orient-item" },
          /* @__PURE__ */ React.createElement(
            "span",
            { className: "orient-num" },
            i + 1,
          ),
          /* @__PURE__ */ React.createElement("p", null, it),
        ),
      ),
    ),
    /* @__PURE__ */ React.createElement(
      "div",
      {
        style: {
          fontWeight: 700,
          color: "var(--verde-escuro)",
          fontSize: 14,
          margin: "18px 0 4px",
        },
      },
      ORIENTACOES.individual.titulo,
    ),
    /* @__PURE__ */ React.createElement(
      "ul",
      { className: "orient-list" },
      ORIENTACOES.individual.itens.map((it, i) =>
        /* @__PURE__ */ React.createElement(
          "li",
          { key: i, className: "orient-item" },
          /* @__PURE__ */ React.createElement(
            "span",
            { className: "orient-num" },
            i + 1,
          ),
          /* @__PURE__ */ React.createElement("p", null, it),
        ),
      ),
    ),
    !restrito &&
      /* @__PURE__ */ React.createElement(
        React.Fragment,
        null,
        /* @__PURE__ */ React.createElement(
          "div",
          {
            style: {
              fontWeight: 700,
              color: "var(--verde-escuro)",
              fontSize: 14,
              margin: "18px 0 4px",
            },
          },
          ORIENTACOES.coletivo.titulo,
        ),
        /* @__PURE__ */ React.createElement(
          "ul",
          { className: "orient-list" },
          ORIENTACOES.coletivo.itens.map((it, i) =>
            /* @__PURE__ */ React.createElement(
              "li",
              { key: i, className: "orient-item" },
              /* @__PURE__ */ React.createElement(
                "span",
                { className: "orient-num" },
                i + 1,
              ),
              /* @__PURE__ */ React.createElement("p", null, it),
            ),
          ),
        ),
      ),
    /* @__PURE__ */ React.createElement(
      "div",
      { className: "cmg-aviso" },
      /* @__PURE__ */ React.createElement("div", {
        className: "cmg-aviso-icon",
        "aria-hidden": "true",
      }),
      /* @__PURE__ */ React.createElement(
        "p",
        { className: "cmg-aviso-texto" },
        ORIENTACOES.callout,
      ),
    ),
    /* @__PURE__ */ React.createElement(
      "div",
      { className: "legend" },
      /* @__PURE__ */ React.createElement(
        "span",
        null,
        /* @__PURE__ */ React.createElement("span", { className: "req" }, "*"),
        " Campo de preenchimento obrigatório",
      ),
      /* @__PURE__ */ React.createElement(
        "span",
        null,
        /* @__PURE__ */ React.createElement("span", { className: "req" }, "**"),
        " Obrigatório para pessoa física",
      ),
    ),
  );
}
