function TabTipo({ ctx }) {
  const {
    aba,
    setAba,
    modalidade,
    setModalidade,
    atend,
    setAtend,
    prop,
    setProp,
    corr,
    setCorr,
    obra,
    setObra,
    gerador,
    setGerador,
    obs,
    setObs,
    cepStatus,
    setCepStatus,
    cnpjStatus,
    setCnpjStatus,
    logoPDF,
    setLogoPDF,
    ucsDet,
    setUcsDet,
    ucBlocos,
    setUcBlocos,
    blocos,
    setBlocos,
    abas,
    buscarCEP,
    buscarCNPJ,
    coletivo,
    coordObrigatoria,
    coordPreenchida,
    demandaPrevTotal,
    demandaTotalGeral,
    disjGeralObrigatorio,
    docInfo,
    gerarPDF,
    hibrido,
    idx,
    irAnt,
    irProx,
    isAlteracaoColetivo,
    maiorCorrenteUC,
    multiTorres,
    opcoesDisjGeral,
    pessoaFisica,
    prevTotalKw,
    redeMono,
    rural,
    replicarPrevTodas,
    replicarPrevTorre,
    replicarPrimeiro,
    replicarUC1Coletivo,
    replicarUC1Torre,
    setBloco,
    setBlocoPrev,
    setTorre,
    setUcDet,
    setUcTorre,
    restrito,
    setUcTorrePrev,
    sincronizarUCsTorre,
    totalUcsEmpreendimento,
    trocaDisjGeral,
    validacaoDisjuntores,
    validacaoHibrido,
    solicitacoesPermitidas,
  } = ctx;
  return /* @__PURE__ */ React.createElement(
    Card,
    {
      eyebrow: "Etapa " + ctx.etapaNum,
      title: "Dados para contato",
      sub: "Preencha os dados de contato da pessoa responsável pelo empreendimento.",
    },
    /* @__PURE__ */ React.createElement(
      "div",
      { className: "grid grid-2" },
      /* Nome → E-mail */
      /* @__PURE__ */ React.createElement(
        Field,
        { label: "Nome Completo (sem abreviações)", req: true },
        /* @__PURE__ */ React.createElement(Inp, {
          value: prop.nome,
          onChange: (e) => setProp({ ...prop, nome: e.target.value }),
        }),
      ),
      /* @__PURE__ */ React.createElement(
        Field,
        { label: "E-mail", req: true },
        /* @__PURE__ */ React.createElement(Inp, {
          type: "email",
          value: prop.email,
          onChange: (e) => setProp({ ...prop, email: e.target.value }),
        }),
      ),
      /* @__PURE__ */ React.createElement(
        Field,
        { label: "Celular", req: true },
        /* @__PURE__ */ React.createElement(Inp, {
          value: prop.celular,
          onChange: (e) =>
            setProp({
              ...prop,
              celular: mascararCelular(e.target.value),
            }),
        }),
      ),
    ),
  );
}
